apiVersion: v1
kind: Service
metadata:
  name: auth-api
  labels:
    app: auth-api
  annotations:
    "consul.hashicorp.com/service-name": "auth-api"
spec:
  ports:
    - port: 5825
      targetPort: 5825
      protocol: TCP
  selector:
    app: auth-api
