apiVersion: v1
kind: Service
metadata:
  name: cart-api
  labels:
    app: cart-api
  annotations:
    "consul.hashicorp.com/service-name": "cart-api"
spec:
  ports:
    - port: 5823
      targetPort: 5823
      protocol: TCP
  selector:
    app: cart-api
