apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-api
  labels:
    app: cart-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-api
  template:
    metadata:
      labels:
        app: cart-api
      annotations:
        "consul.hashicorp.com/service-name": "cart-api"
    spec:
      containers:
      - name: cart-api
        image: "jubican/javaperks-cart-api:1.1.2"
        imagePullPolicy: Always
        ports:
        - containerPort: 5823
        env:
          - name: LOCALHOST_ONLY
            value: "true"
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: env-values
                key: aws-region
          - name: DDB_TABLE_NAME
            valueFrom:
              configMapKeyRef:
                name: env-values
                key: table-cart
        # livenessProbe:
        #   httpGet:
        #     path: /_health_check
        #     port: 5822
        #   initialDelaySeconds: 10
        #   periodSeconds: 30
        resources:
          limits:
            cpu: 300m
          requests:
            cpu: 100m
            memory: 100Mi
