apiVersion: v1
kind: Service
metadata:
  name: order-api
  labels:
    app: order-api
  annotations:
    "consul.hashicorp.com/service-name": "order-api"
spec:
  ports:
    - port: 5824
      targetPort: 5824
      protocol: TCP
  selector:
    app: order-api
