apiVersion: v1
kind: Service
metadata:
  name: product-api
  labels:
    app: product-api
  annotations:
    "consul.hashicorp.com/service-name": "product-api"
spec:
  ports:
    - port: 5821
      targetPort: 5821
      protocol: TCP
  selector:
    app: product-api
